var SchoolConstants = {
  RECEIVE_ALL_SCHOOL_MEMBERS: "RECEIVE_ALL_SCHOOL_MEMBERS",
  RECEIVE_ALL_CURRENT_USER_SCHOOL_MEMBERS: "RECEIVE_ALL_CURRENT_USER_SCHOOL_MEMBERS",
  RECEIVE_SINGLE_CURRENT_USER_SCHOOL_MEMBER: "RECEIVE_SINGLE_CURRENT_USER_SCHOOL_MEMBER"
};

module.exports = SchoolConstants;
